version: '3.8'

services:
  coreness-service:
    build:
      context: ..                    # Контекст сборки - корень проекта
      dockerfile: docker/Dockerfile  # Путь к Dockerfile
    container_name: coreness-container
    volumes:
      - ../:/workspace               # Монтируем весь проект в /workspace
    command: ["tail", "-f", "/dev/null"]  # Держим контейнер живым
    restart: unless-stopped
