# Default пресет - базовые команды
# Этот пресет используется как fallback если указанный пресет не найден

start:
  actions:
    - type: send
      text: "Привет! Добро пожаловать в бота!"
      inline:
        - [{"Меню": "main_menu"}]

help:
  actions:
    - type: send
      text: "Справка по командам:\n\n/start - начать работу с ботом\n/help - показать эту справку"
      inline:
        - [{"Назад": "start"}]
