# Default ะฟัะตัะตั - ะฑะฐะทะพะฒัะต ะบะพะผะฐะฝะดั
# ะญัะพั ะฟัะตัะตั ะธัะฟะพะปัะทัะตััั ะบะฐะบ fallback ะตัะปะธ ัะบะฐะทะฐะฝะฝัะน ะฟัะตัะตั ะฝะต ะฝะฐะนะดะตะฝ

start:
  actions:
    - type: send
      text: "๐ ะัะธะฒะตั!\n\n๐ ะัะฑะตัะธัะต ะดะตะนััะฒะธะต:"
      inline:
        - [{"๐ ะะตะฝั": "main_menu"}, {"๐ ะกะฟัะฐะฒะบะฐ": "help"}]

help:
  actions:
    - type: send
      text: "๐ ะกะฟัะฐะฒะบะฐ\n\n๐น /start - ะฝะฐัะฐัั ัะฐะฑะพัั\n๐น /help - ะฟะพะบะฐะทะฐัั ัะฟัะฐะฒะบั"
      inline:
        - [{"๐ ะะฐะทะฐะด": "start"}]
